### ISSUE TITLE
Question about what the camera is able to do.

### ISSUE THREAD

**Issue by dragonslayer452** [Seeed-Studio/OSHW-reCamera-Series#4]
With the 1 TOPS AI processer can the camera alone run MiDaS AI (it's a AI that can give you depth with one camera ) if not is there a way for you to connect two cameras to the same baseboard so you can have stereo vision for depth sensing

**Comment by litxaohu** [comment]
We haven't tested MiDaS AI, but theoretically, you can design a sensor board to integrate two cameras onto a single baseboard, as the top board has four differential signal lines. It's important to consider whether the PCB size is sufficient for installation and to address any potential heat dissipation issues.

**Comment by yuking926** [comment]
你们好，这个相机你们已经在测试了吗，为什么我找不到核心板的任何pcb信息，我也想要制作一个这样的相机来学习
