### ISSUE TITLE
C1_2002w没有资料吗？

### ISSUE THREAD

**Issue by yuking926** [Seeed-Studio/OSHW-reCamera-Series#5]

**Comment by baorepo** [comment]
谢谢的你关注，我们还在规划中，如果有适合的方案，我们及时更新。

**Comment by yuking926** [comment]
可是[C1_2002w]的核心板不是已经有了吗，我想使用这个先进的视觉相机进行开发，或者上面渠道能够买到成品

**Comment by ChangeClock** [comment]
这个产品将在下个月上线销售，C1-2002w的资料我们会近期同步更新
