### ISSUE TITLE
[Bug] Unable to manually update the firmware

### ISSUE THREAD

**Issue by O-J1** [Seeed-Studio/OSHW-reCamera-Series#9]
### What did you observe

1. Accessed the device via https://192.168.42.1
2. Clicked on terminal
3. Entered the following: `/mnt/system/upgrade.sh latest https://github.com/Seeed-Studio/reCamera-OS/releases/latest`
4. Result ```Step1: Parse upgrade url
Failed: unknown url(https://github.com/Seeed-Studio/reCamera-OS/releases/latest).```

I also tried SSH'ing in and that also didnt work.

### Expected result
Ability to upgrade firmware.

**Comment by Lesords** [comment]
Hello, 

What version of the system are you using?

**Comment by Lesords** [comment]
The problem appears to be that your device is not connected to the Internet.

**Comment by O-J1** [comment]
> The problem appears to be that your device is not connected to the Internet.

Ah so when plugged in over usbc to a computer that is connected to the internet the device itself cannot get internet? My mistake 🫡

**Comment by Lesords** [comment]
Hello,

I'm going to close this issue, feel free to re-open it if you have any other questions.
